# Generated by Django 3.0.5 on 2020-04-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200428_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='users/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user_comment',
            name='time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_comment',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='New_User_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User')),
            ],
        ),
    ]
