# Generated by Django 3.0.5 on 2020-04-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Archi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='archi/')),
            ],
        ),
        migrations.AlterField(
            model_name='new_user_comment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_User'),
        ),
        migrations.AlterField(
            model_name='test1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_User'),
        ),
    ]
