# Generated by Django 3.0.5 on 2020-04-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20200428_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=2000)),
                ('photo', models.ImageField(blank=True, upload_to='style/')),
            ],
        ),
        migrations.CreateModel(
            name='New_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=2000)),
                ('archi', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_Archi')),
                ('style', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_Style')),
            ],
        ),
    ]
