# Generated by Django 3.0.5 on 2020-04-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
