# Generated by Django 3.0.5 on 2020-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
