# Generated by Django 3.0.5 on 2020-04-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_new_building_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_User_Building_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_Building')),
            ],
        ),
    ]
