# Generated by Django 3.0.5 on 2020-05-01 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0015_test_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_User_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('photo', models.ImageField(blank=True, upload_to='comment_photo/')),
                ('building', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_Building')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
