# Generated by Django 3.0.5 on 2020-05-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_my_new_user_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Style_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=2000)),
                ('style', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_Style')),
            ],
        ),
    ]
