# Generated by Django 3.0.5 on 2020-04-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_new_building_new_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_Building_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='buildings/')),
                ('building', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.New_Building')),
            ],
        ),
    ]
